/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.sp.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Consultant service. Represents a row in the &quot;SP_Consultant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>si.bintegra.sp.model.impl.ConsultantModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>si.bintegra.sp.model.impl.ConsultantImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Consultant
 * @generated
 */
@ProviderType
public interface ConsultantModel extends BaseModel<Consultant> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a consultant model instance should use the {@link Consultant} interface instead.
	 */

	/**
	 * Returns the primary key of this consultant.
	 *
	 * @return the primary key of this consultant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this consultant.
	 *
	 * @param primaryKey the primary key of this consultant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this consultant.
	 *
	 * @return the ID of this consultant
	 */
	public long getId();

	/**
	 * Sets the ID of this consultant.
	 *
	 * @param id the ID of this consultant
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this consultant.
	 *
	 * @return the user ID of this consultant
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this consultant.
	 *
	 * @param userId the user ID of this consultant
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this consultant.
	 *
	 * @return the user uuid of this consultant
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this consultant.
	 *
	 * @param userUuid the user uuid of this consultant
	 */
	public void setUserUuid(String userUuid);

	@Override
	public Consultant cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}