/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.sp.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PackageOffer service. Represents a row in the &quot;SP_PackageOffer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>si.bintegra.sp.model.impl.PackageOfferModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>si.bintegra.sp.model.impl.PackageOfferImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PackageOffer
 * @generated
 */
@ProviderType
public interface PackageOfferModel extends BaseModel<PackageOffer> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a package offer model instance should use the {@link PackageOffer} interface instead.
	 */

	/**
	 * Returns the primary key of this package offer.
	 *
	 * @return the primary key of this package offer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this package offer.
	 *
	 * @param primaryKey the primary key of this package offer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this package offer.
	 *
	 * @return the ID of this package offer
	 */
	public long getId();

	/**
	 * Sets the ID of this package offer.
	 *
	 * @param id the ID of this package offer
	 */
	public void setId(long id);

	/**
	 * Returns the offer ID of this package offer.
	 *
	 * @return the offer ID of this package offer
	 */
	public Long getOfferId();

	/**
	 * Sets the offer ID of this package offer.
	 *
	 * @param offerId the offer ID of this package offer
	 */
	public void setOfferId(Long offerId);

	/**
	 * Returns the full duration of this package offer.
	 *
	 * @return the full duration of this package offer
	 */
	public Long getFullDuration();

	/**
	 * Sets the full duration of this package offer.
	 *
	 * @param fullDuration the full duration of this package offer
	 */
	public void setFullDuration(Long fullDuration);

	/**
	 * Returns the discount duration of this package offer.
	 *
	 * @return the discount duration of this package offer
	 */
	public Long getDiscountDuration();

	/**
	 * Sets the discount duration of this package offer.
	 *
	 * @param discountDuration the discount duration of this package offer
	 */
	public void setDiscountDuration(Long discountDuration);

	/**
	 * Returns the base price of this package offer.
	 *
	 * @return the base price of this package offer
	 */
	public Double getBasePrice();

	/**
	 * Sets the base price of this package offer.
	 *
	 * @param basePrice the base price of this package offer
	 */
	public void setBasePrice(Double basePrice);

	/**
	 * Returns the discount price of this package offer.
	 *
	 * @return the discount price of this package offer
	 */
	public Double getDiscountPrice();

	/**
	 * Sets the discount price of this package offer.
	 *
	 * @param discountPrice the discount price of this package offer
	 */
	public void setDiscountPrice(Double discountPrice);

	/**
	 * Returns the active of this package offer.
	 *
	 * @return the active of this package offer
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this package offer.
	 *
	 * @param active the active of this package offer
	 */
	public void setActive(Boolean active);

	@Override
	public PackageOffer cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}