/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.sp.model.impl;

import si.bintegra.sp.model.Consultant;
import si.bintegra.sp.service.ConsultantLocalServiceUtil;

/**
 * The extended model base implementation for the Consultant service. Represents a row in the &quot;SP_Consultant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsultantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsultantImpl
 * @see Consultant
 * @generated
 */
public abstract class ConsultantBaseImpl
	extends ConsultantModelImpl implements Consultant {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consultant model instance should use the <code>Consultant</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ConsultantLocalServiceUtil.addConsultant(this);
		}
		else {
			ConsultantLocalServiceUtil.updateConsultant(this);
		}
	}

}