/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.sp.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import si.bintegra.sp.model.ConsultantCustomer;
import si.bintegra.sp.model.ConsultantCustomerModel;

/**
 * The base model implementation for the ConsultantCustomer service. Represents a row in the &quot;SP_ConsultantCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConsultantCustomerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsultantCustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsultantCustomerImpl
 * @generated
 */
@JSON(strict = true)
public class ConsultantCustomerModelImpl
	extends BaseModelImpl<ConsultantCustomer>
	implements ConsultantCustomerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consultant customer model instance should use the <code>ConsultantCustomer</code> interface instead.
	 */
	public static final String TABLE_NAME = "SP_ConsultantCustomer";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"consultantId", Types.BIGINT},
		{"customerId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("consultantId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SP_ConsultantCustomer (id_ LONG not null primary key,consultantId LONG,customerId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table SP_ConsultantCustomer";

	public static final String ORDER_BY_JPQL =
		" ORDER BY consultantCustomer.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SP_ConsultantCustomer.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONSULTANTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CUSTOMERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ConsultantCustomerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConsultantCustomer.class;
	}

	@Override
	public String getModelClassName() {
		return ConsultantCustomer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConsultantCustomer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConsultantCustomer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConsultantCustomer, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConsultantCustomer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConsultantCustomer, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConsultantCustomer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConsultantCustomer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConsultantCustomer, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConsultantCustomer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ConsultantCustomer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ConsultantCustomer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ConsultantCustomer, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ConsultantCustomer, Object>>();
		Map<String, BiConsumer<ConsultantCustomer, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ConsultantCustomer, ?>>();

		attributeGetterFunctions.put("id", ConsultantCustomer::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<ConsultantCustomer, Long>)ConsultantCustomer::setId);
		attributeGetterFunctions.put(
			"consultantId", ConsultantCustomer::getConsultantId);
		attributeSetterBiConsumers.put(
			"consultantId",
			(BiConsumer<ConsultantCustomer, Long>)
				ConsultantCustomer::setConsultantId);
		attributeGetterFunctions.put(
			"customerId", ConsultantCustomer::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId",
			(BiConsumer<ConsultantCustomer, Long>)
				ConsultantCustomer::setCustomerId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public Long getConsultantId() {
		return _consultantId;
	}

	@Override
	public void setConsultantId(Long consultantId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_consultantId = consultantId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalConsultantId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("consultantId"));
	}

	@JSON
	@Override
	public Long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(Long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalCustomerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("customerId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ConsultantCustomer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConsultantCustomer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ConsultantCustomer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConsultantCustomerImpl consultantCustomerImpl =
			new ConsultantCustomerImpl();

		consultantCustomerImpl.setId(getId());
		consultantCustomerImpl.setConsultantId(getConsultantId());
		consultantCustomerImpl.setCustomerId(getCustomerId());

		consultantCustomerImpl.resetOriginalValues();

		return consultantCustomerImpl;
	}

	@Override
	public ConsultantCustomer cloneWithOriginalValues() {
		ConsultantCustomerImpl consultantCustomerImpl =
			new ConsultantCustomerImpl();

		consultantCustomerImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		consultantCustomerImpl.setConsultantId(
			this.<Long>getColumnOriginalValue("consultantId"));
		consultantCustomerImpl.setCustomerId(
			this.<Long>getColumnOriginalValue("customerId"));

		return consultantCustomerImpl;
	}

	@Override
	public int compareTo(ConsultantCustomer consultantCustomer) {
		long primaryKey = consultantCustomer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ConsultantCustomer)) {
			return false;
		}

		ConsultantCustomer consultantCustomer = (ConsultantCustomer)object;

		long primaryKey = consultantCustomer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ConsultantCustomer> toCacheModel() {
		ConsultantCustomerCacheModel consultantCustomerCacheModel =
			new ConsultantCustomerCacheModel();

		consultantCustomerCacheModel.id = getId();

		Long consultantId = getConsultantId();

		if (consultantId != null) {
			consultantCustomerCacheModel.consultantId = consultantId;
		}

		Long customerId = getCustomerId();

		if (customerId != null) {
			consultantCustomerCacheModel.customerId = customerId;
		}

		return consultantCustomerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConsultantCustomer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConsultantCustomer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConsultantCustomer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ConsultantCustomer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ConsultantCustomer>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ConsultantCustomer.class, ModelWrapper.class);

	}

	private long _id;
	private Long _consultantId;
	private Long _customerId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ConsultantCustomer, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ConsultantCustomer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("consultantId", _consultantId);
		_columnOriginalValues.put("customerId", _customerId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("consultantId", 2L);

		columnBitmasks.put("customerId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ConsultantCustomer _escapedModel;

}